"use strict";
module.exports = {
    config: {
        updateChannel: 'stable',
        fontSize: 12,
        fontFamily: '"Hasklug Nerd Font", "Hack Nerd Font" ,"Menlo" , "DejaVu Sans Mono", "Consolas", "Lucida Console", "monospace"',
        fontWeight: 'normal',
        fontWeightBold: 'bold',
        lineHeight: 1,
        letterSpacing: 0,
        cursorColor: 'rgba(248,28,229,0.8)',
        cursorAccentColor: '#000',
        cursorShape: 'BLOCK',
        cursorBlink: false,
        foregroundColor: '#fff',
        backgroundColor: '#000',
        selectionColor: 'rgba(248,28,229,0.3)',
        borderColor: '#333',
        css: '',
        termCSS: '',
        workingDirectory: '',
        showHamburgerMenu: '',
        showWindowControls: '',
        padding: '12px 12px',
        colors: {
            black: '#2a2b48',
            red: '#301934',
            green: '#810080',
            yellow: '#C839C5',
            blue: '#20313a',
            magenta: '#C839C5',
            cyan: '#800080',
            white: '#583354',
            lightBlack: '#686868',
            lightRed: '#FD6F6B',
            lightGreen: '#C839C5',
            lightYellow: '#C839C5',
            lightBlue: '#6A76FB',
            lightMagenta: '#FD7CFC',
            lightCyan: '#68FDFE',
            lightWhite: '#800080',
            limeGreen: '#C839C5',
            lightCoral: '#F08080',
        },
        shell: '/usr/bin/zsh',
        shellArgs: ['--login'],
        env: {},
        bell: 'SOUND',
        copyOnSelect: false,
        defaultSSHApp: true,
        quickEdit: false,
        macOptionSelectionMode: 'vertical',
        webGLRenderer: true,
        webLinksActivationKey: '',
        disableLigatures: true,
        disableAutoUpdates: false,
        screenReaderMode: false,
        preserveCWD: true,
	backgroundImage: "/home/achux21/Pictures/term.png"

    },
    plugins: ["hyperpower", "hyper-background"],
    localPlugins: [],
    keymaps: {
    },
};
// Hyper-Config by : ACHUX21 https://github.com/ACHUX21
